Add Free Time feature to model
AY2324S1-CS2103T-W12-4/tp pull request #45
Opened 2023-10-05 16:08 UTC by andrefoo

TimetaBRO needs to know a person's free time to identify
 when they are available as lunch buddies.

 Let's add a FreeTime class in the model.
 For storage purposes, add JsonAdaptedFreeTime and
 adapt Person and JsonAdaptedPerson classes to compose of
  a Set of free times.

 A few cascading errors have been addressed, adding
 freetime support to PersonBuilders and Data and Util classes.

2023-10-11 16:13 UTC, andrefoo commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +import seedu.address.model.person.*;
don't do this

2023-10-13 04:19 UTC, owenyeo requested changes
Change import statements

2023-10-13 04:19 UTC, owenyeo commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +import seedu.address.model.person.*;
Yes

2023-10-13 04:19 UTC, owenyeo commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +import seedu.address.model.person.*;
Another mistake here

2023-10-13 04:19 UTC, owenyeo commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +import seedu.address.model.person.*;
Same as above

2023-10-13 04:19 UTC, owenyeo commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +import static seedu.address.logic.parser.CliSyntax.*;
Same as above

2023-10-13 04:19 UTC, owenyeo commented on src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Same as above

2023-10-13 04:19 UTC, owenyeo commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +import seedu.address.model.person.*;
Same as above

2023-10-13 04:19 UTC, owenyeo commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
> +import static seedu.address.logic.parser.CliSyntax.*;
Same as above

2023-10-13 04:42 UTC, andrefoo commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
> +import static seedu.address.logic.parser.CliSyntax.*;
okay done

2023-10-13 14:23 UTC, owenyeo approved these changes
LGTM

2023-10-13 14:25 UTC, merged